version: '2'
services:
  app:
    build:
      context: ./
      args:
        - githubUsername=<YourGithubUserNameForClone>
        - githubPassword=<YourGithubPasswordForClone>
      dockerfile: Dockerfile
    env_file:
      - http-mqtt-bridge.env
    ports:
      - "5000:5000"
    container_name: http-to-mqtt
    restart: unless-stopped
    image: http-to-mqtt-image

